### ISSUE TITLE
Automatische Typkonvertierung String -> arse.Input

### ISSUE THREAD

**Issue by lucc** [lucc/ulang-tiny#1]
@gernst

Ich habe angefangen Tests zu schreiben und mich gewundert, was für eine Magie in https://github.com/lucc/ulang-tiny/blob/develop/ulang/src/ulang/Exec.scala#L138-L152 passiert, da ich in den Tests einen extra Konvertierungsschritt brauche: https://github.com/lucc/ulang-tiny/blob/tests/ulang/test/src/ParseTest.scala#L7

**Comment by gernst** [comment]
https://github.com/gernst/arse/blob/ae5cf8553fb33b6b65bfb94a43873d8f2f12b6a5/arse/src/arse/package.scala#L11

`import arse.input` oder `import arse._` damit wird die Konvertierung von `String` nach `Input` sichtbar.

Du brauchst aber noch ein `implicit val` oder `implicit object` vom Typ `Whitespace` im Scope, z.B.: mit `import ulang.Parse.whitespace`
